services:
  simple-shop:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: simple-shop

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      DATABASE_URL: "file:./dev.db"

    restart: unless-stopped